//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GEOBOX.OSC.DisplayModelEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GEOBOX.OSC.DisplayModelEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV wurde erfolgreich erstellt..
        /// </summary>
        public static string CSVCreationSuccess {
            get {
                return ResourceManager.GetString("CSVCreationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GEOBOX Darstellungsmodell Editor.
        /// </summary>
        public static string genModulName {
            get {
                return ResourceManager.GetString("genModulName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einige Layerfiles wurden nicht gefunden....
        /// </summary>
        public static string LayersNotFound {
            get {
                return ResourceManager.GetString("LayersNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.A..
        /// </summary>
        public static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entferne Extended-Data (Layers)..
        /// </summary>
        public static string RemoveExtendedData {
            get {
                return ResourceManager.GetString("RemoveExtendedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter entfernen (Layers)..
        /// </summary>
        public static string RemoveFilter {
            get {
                return ResourceManager.GetString("RemoveFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbenutzte Gruppe &quot;{0}&quot; entfernen (TBDMMAP).
        /// </summary>
        public static string RemoveUnusedLayerGroup {
            get {
                return ResourceManager.GetString("RemoveUnusedLayerGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entferne ViewPort (TBDMMAP)..
        /// </summary>
        public static string RemoveViewPort {
            get {
                return ResourceManager.GetString("RemoveViewPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setzte Datasource, Username und Viewport (Layers).
        /// </summary>
        public static string SetAttributes {
            get {
                return ResourceManager.GetString("SetAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setzte Datasource auf &quot;{0}&quot; (TBDMMAP)..
        /// </summary>
        public static string SetDatasource {
            get {
                return ResourceManager.GetString("SetDatasource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setzte WindowStatus (TBDMMAP)..
        /// </summary>
        public static string SetWindowState {
            get {
                return ResourceManager.GetString("SetWindowState", resourceCulture);
            }
        }
    }
}
